# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cws < Formula
  desc "A CLI for managing Chrome Web Store extensions"
  homepage "https://vaughnbosu.github.io/cws-cli/"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v1.1.0/cws_darwin_amd64.tar.gz"
      sha256 "bddbe712d43bb892dd978b70d8d2921fd2289765a3ed8353bc93d1c7077db341"

      define_method(:install) do
        bin.install "cws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v1.1.0/cws_darwin_arm64.tar.gz"
      sha256 "afcafd486b6914ffc545826db854f7195a566cc37f4d6e69de1f9aef76bb4c3a"

      define_method(:install) do
        bin.install "cws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v1.1.0/cws_linux_amd64.tar.gz"
      sha256 "cdc924dc95208f28cf0151649e494bba777168176306bc76efc41b2e66e206a9"
      define_method(:install) do
        bin.install "cws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v1.1.0/cws_linux_arm64.tar.gz"
      sha256 "31ca7d22dad4a4b47342430909afbcc9a8387c50d1e09b10984b1c7ef3bdb628"
      define_method(:install) do
        bin.install "cws"
      end
    end
  end

  test do
    system "#{bin}/cws", "version"
  end
end
